name: 应用翻译文件

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  apply-translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 配置 SSH 私钥
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" >./ssh_privkey
          chmod 600 ./ssh_privkey
      - name: 上传翻译文件
        run: |
          DIRS=("authserver_15000" "survival_10001" "missilewars_10002" "dungeun_10003")
          for dir in ${DIRS[@]}; do
            scp -o StrictHostKeyChecking=no -P ${{ secrets.SSH_PORT }} -i ./ssh_privkey -r ./translations/* toilet@${{ secrets.SSH_HOST }}:/home/toilet/test/$dir/translations/
          done
