name: 应用翻译文件

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  apply-translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 配置 SSH 私钥
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
      - name: 上传翻译文件
        run: |
          DIRS=("authserver_15000" "survival_10001" "missilewars_10002" "dungeun_10003")
          for dir in ${DIRS[@]}; do
            scp -P ${{ secrets.SSH_PORT }} -i ~/.ssh/id_ed25519 -r ./translations/* toilet@${{ secrets.SSH_HOST }}:/home/toilet/test/$dir/translations/
          done
